[package]
org = "ballerinax"
name = "list_account_exports"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[dependency]]
name="mailchimp.marketing"
org="ballerinax"
version="1.0.0"
repository="local"
