[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "mailchimp.marketing"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["mailchimp", "marketing", "email", "campaigns", "ballerina", "connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mailchimp.marketing"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
